# Generated by Django 4.2.2 on 2023-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institutes",
            fields=[
                (
                    "id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("TLR", models.DecimalField(decimal_places=2, max_digits=5)),
                ("RPC", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "GO",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "OI",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "PERCEPTION",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("city", models.CharField(max_length=1000)),
                ("state", models.CharField(max_length=1000)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("rank", models.IntegerField(default=1)),
            ],
        ),
    ]
